# Acquia alike stack
#
# - Apache 2.4
# - MySQL 5.6
# - PHP 7.2
# - Varnish 4.1
# - Memcached 1.4
# - ApacheSolr 4.5

version: "3.9"

services:
  # http(s)://VIRTUAL_HOST
  web:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: apache
    depends_on:
      - cli

  db:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: mysql

  cli:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: cli

  # http(s)://varnish.VIRTUAL_HOST
  varnish:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: varnish
    # Pin Varnish version
    image: ${VARNISH_IMAGE:-docksal/varnish:4.1-2.0}
    depends_on:
      - web

  memcached:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: memcached

  # http(s)://solr.VIRTUAL_HOST/solr
  solr:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: solr
    # Pin Solr version
    image: ${SOLR_IMAGE:-docksal/solr:1.0-solr4}
